### PR TITLE
Fix URL constructor.

### PR DESCRIPTION
**Pull request by pazguille**
Hi! The following PR fixs an error with the URL.
```
 TypeError: URL is not a constructor
```

### CODE REVIEW

**Comment by popeindustries** [comment]
Nice catch, thanks!

**Comment by popeindustries** [comment]
Sorry @pazguille, I was a little trigger happy! `URL` is the correct [class for the WHATWG URL standard API](https://nodejs.org/api/url.html#url_the_whatwg_url_api). This was added in Node 7, and is the same as in the browser. What version of Node were you running when you got the error? `sw-test-env` only works with Node 7 and above for this reason.

**Comment by pazguille** [comment]
Hi @popeindustries, I'm using node LTS (v6.11.1) version. I didn't know that only works with version 7. It's a good requirement to add into the README.

**Comment by popeindustries** [comment]
Will do. There is this in `package.json`: `"engines": {  "node": ">=7" }`, so there should be a warning on install, but I guess it's not always very visible.

**Comment by pazguille** [comment]
Sure! This is a great module and I would like to use on my work (a big company) where we are using LTS version. What do you think about support `Url` and `URL`? This could be great to us.

**Comment by popeindustries** [comment]
yeah, it would be nice to support both, but the problem is that the legacy `Url` class used by Node 6 isn't used directly (instances are constructed with `url.parse()`, not `new URL()`), so they aren't fully compatible. I can open an issue and see if others are having problems, but Node 8 is supposed to go LTS at the end of this month, so maybe it's a problem that will go away on it's own?

**Pull request merged**
